### PR TITLE
Make $PWD between TestStep and TestAssert commands consistent

### LINKED ISSUE #322: Inconsistent $PWD between TestStep and TestAssert commands
**What happened**:

I start some `commands:` from a `TestAssert` and a `TestStep`. Current working directory for the former is the directory I started `kuttl` from, while for the latter it's the directory where the step file is located.

**What you expected to happen**:

Current working directory should be the same for both cases.

**How to reproduce it (as minimally and precisely as possible)**:

```
~ $ head -n 999 tests/quick/very/00-*
==> tests/quick/very/00-assert.yaml <==
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
commands:
- command: echo assert command
- command: pwd
- script: |
   echo assert script
   pwd

==> tests/quick/very/00-image-pull-secrets.yaml <==
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
# Set up operand image pull secrets for development.
- script: |
    echo step script
    pwd
- command: echo step command
- command: pwd
~ $ ./bin/kubectl-kuttl-0.11.0 test ./tests/quick
2021/09/14 08:58:56 kutt-test config testdirs is overridden with args: [ ./tests/quick ]
=== RUN   kuttl
    harness.go:457: starting setup
    harness.go:248: running tests using configured kubeconfig.
    harness.go:285: Successful connection to cluster at: https://kubernetes.docker.internal:6443
    harness.go:353: running tests
    harness.go:74: going to run test suite with timeout of 300 seconds for each step
    harness.go:365: testsuite: ./tests/quick has 1 tests
=== RUN   kuttl/harness
=== RUN   kuttl/harness/very
=== PAUSE kuttl/harness/very
=== CONT  kuttl/harness/very
    logger.go:42: 08:58:58 | very | Creating namespace: kuttl-test-smiling-doberman
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | starting test step 0-image-pull-secrets
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [sh -c echo step script
        pwd
        ]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | step script
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | /Users/marcin/tests/quick/very
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [echo step command]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | step command
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [pwd]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | /Users/marcin/tests/quick/very
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [echo assert command]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | assert command
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [pwd]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | /Users/marcin
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | running command: [sh -c echo assert script
        pwd
        ]
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | assert script
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | /Users/marcin
    logger.go:42: 08:58:58 | very/0-image-pull-secrets | test step completed 0-image-pull-secrets
    logger.go:42: 08:58:58 | very | very events from ns kuttl-test-smiling-doberman:
    logger.go:42: 08:58:58 | very | Deleting namespace: kuttl-test-smiling-doberman
=== CONT  kuttl
    harness.go:399: run tests finished
    harness.go:508: cleaning up
    harness.go:563: removing temp folder: ""
--- PASS: kuttl (2.76s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/very (0.78s)
PASS
~ $ 
```

**Anything else we need to know?**:

**Environment**:
- KUTTL version (use `kubectl kuttl version`): 0.11.1
- OS (e.g. from /etc/os-release): MacOS 11.6

### PR DESCRIPTION
**Pull request by stuggi**
**What this PR does / why we need it**:

The $PWD is different when running commands in TestStep and TestAssert which makes it required e.g. to use abs path to reference a script. This change aligns the path passed into testutils.RunAssertCommands() to be the same as to testutils.RunCommands().

Fixes #322

### CODE REVIEW

File: pkg/test/step_integration_test_data/assert_commands/path_script/test/script.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+echo -n "$0 $@"
```
Comment (porridge) [inline pkg/test/step_integration_test_data/assert_commands/path_script/test/script.sh:1]: IIRC `[[` is not supported by all shells, so we should probably have an explicit shebang line:

```suggestion
#!/bin/bash
echo -n "$0 $@"
```

File: pkg/test/step_integration_test.go [hunk 2]
```diff
@@ -533,3 +533,28 @@ func TestAssertCommandsShouldTimeout(t *testing.T) {
...
+	}
+
+	// Load test assert runs a script via absolute and relative path to the test, so it should run ok, and don't return any errors
+	err := step.LoadYAML("step_integration_test_data/assert_commands/path_script/00-assert.yaml")
+	assert.NoError(t, err)
+
+	errors := step.Run(t, "irrelevant")
+	assert.Equal(t, len(errors), 0)
+
+	// Load the same in a step should behave the same, so it should run ok, and don't return any errors
```
Comment (porridge) [inline pkg/test/step_integration_test.go:554]:
```suggestion
	// TestAssert runs a script via absolute and relative path to the test, so it should run ok, and not return any errors.
	err := step.LoadYAML("step_integration_test_data/assert_commands/path_script/00-assert.yaml")
	assert.NoError(t, err)

	errors := step.Run(t, "irrelevant")
	assert.Equal(t, len(errors), 0)

	// Load the same in a TestStep should behave the same, so it should run ok, and not return any errors.
```

**Review by porridge — CHANGES_REQUESTED** [review]
Thank you for your contribution!
A couple of nitpicks inline.
Also, now that we have this consistent, would you mind adding a note about the CWD to https://github.com/kudobuilder/kuttl/blob/main/docs/testing/reference.md#commands?

File: pkg/test/step_integration_test_data/assert_commands/path_script/test/script.sh (hunk 1 above)
Comment (stuggi) [reply pkg/test/step_integration_test_data/assert_commands/path_script/test/script.sh:3]: done thanks for the pointer

File: pkg/test/step_integration_test.go (hunk 2 above)
Comment (stuggi) [reply pkg/test/step_integration_test.go]: done

File: docs/testing/reference.md [hunk 3]
```diff
@@ -163,3 +163,5 @@ ignoreFailure | bool   | If set, failures will be ignored.
 background    | bool   | If this command is to be started in the background. These are only support in TestSuites.
 skipLogOutput | bool   | If set, the output from the command is *not* logged. Useful for sensitive logs or to reduce noise.
 timeout       | int    | Override the TestSuite timeout for this command (in seconds).
+
+*Note*: The current working directory (CWD) for commend/script is the test directory.
```
Comment (porridge) [inline docs/testing/reference.md:167]:
```suggestion
*Note*: The current working directory (CWD) for `command`/`script` is the test directory.
```

**Review by porridge — APPROVED** [review]
LGTM, just one more nitpick.

File: docs/testing/reference.md (hunk 3 above)
Comment (stuggi) [reply docs/testing/reference.md]: thanks, done
