### PR TITLE
fix: prefer events v1 over v1beta1

### LINKED ISSUE #373: events.k8s.io/v1beta1 Event is deprecated
**What happened**: Installed latest `kuttl` and wrote a test suite, and ran the suite, warning is logged:

```
Warning: events.k8s.io/v1beta1 Event is deprecated in v1.22+, unavailable in v1.25+
```

**What you expected to happen**: No warnings about deprecated APIs

**How to reproduce it (as minimally and precisely as possible)**:

1. Run any `kuttl` test suite on Kubernetes 1.22+

**Anything else we need to know?**: n/a

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.23.5+b463d71`
- KUTTL version (use `kubectl kuttl version`): `0.12.1`
- Cloud provider or hardware configuration: OpenShift 4.10 on baremetal
- OS (e.g. from /etc/os-release): `Ubuntu 20.04.3 LTS`
- Kernel (e.g. `uname -a`): `5.4.0-109-generic`
- Install tools: n/a
- Others: n/a

### LINKED ISSUE #414: events.k8s.io/v1beta1 removal in Kubernetes 1.25
**What would you like to be added**:

Adapt kuttl to use new API version for Events in Kubernetes 1.25+

**Why is this needed**:

Test output shows kuttl is still getting events using the v1beta1 API version. As indicated, this is deprecated in 1.22 and removed in 1.25.

```
Warning: events.k8s.io/v1beta1 Event is deprecated in v1.22+, unavailable in v1.25+
```

### PR DESCRIPTION
**Pull request by eddycharly**
**What this PR does / why we need it**:

This PR gives preference to events v1 over v1beta1 and falls back to v1beta1 if v1 didn't work.

Fixes #373 
Fixes #414

### CODE REVIEW

**Comment by chipzoller** [comment]
Also fixes #414

File: pkg/test/case.go [hunk 1]
```diff
@@ -174,10 +174,10 @@ func (t *Case) CollectEvents(namespace string) {
...
 
-	err = t.collectEventsBeta1(cl, namespace)
+	err = t.collectEventsV1(cl, namespace)
 	if err != nil {
-		t.Logger.Log("Trying with events eventsv1 API...")
-		err = t.collectEventsV1(cl, namespace)
+		t.Logger.Log("Trying with events eventsv1beta1 API...")
+		err = t.collectEventsBeta1(cl, namespace)
 		if err != nil {
 			t.Logger.Log("Trying with events corev1 API...")
```
Comment (iblancasa) [inline pkg/test/case.go:182]: Should the log message be changed?

**Review by iblancasa — CHANGES_REQUESTED** [review]

File: pkg/test/case.go (hunk 1 above)
Comment (eddycharly) [reply pkg/test/case.go:182]: I changed the log message according to the logic change.

**Review by kensipe — APPROVED** [review]
/lgtm
