### PR TITLE
Better Command Error Handling

### LINKED ISSUE #170: Kuttl runs all commands in TestSuite despite a timeout
**What happened**:

```
$ cat <<END > kuttl-test.yaml
apiVersion: kudo.dev/v1alpha1
kind: TestSuite
commands:
        - command: sleep 3
        - command: echo step two
testDirs:
        - empty
timeout: 2
END
$ mkdir empty
$ kubectl kuttl test -v3
=== RUN   kuttl
    kuttl: harness.go:339: starting setup
    kuttl: harness.go:225: running tests using configured kubeconfig.
    kuttl: logger.go:42: 15:22:15 |  | running command: "sleep 3"
    kuttl: logger.go:42: 15:22:15 |  | running command: [sleep 3]
    kuttl: logger.go:42: 15:22:17 |  | running command: "echo step two"
    kuttl: logger.go:42: 15:22:17 |  | running command: [echo step two]
    kuttl: logger.go:42: 15:22:17 |  | step two
    kuttl: harness.go:458: fatal error running commands: [command "sleep 3" exceeded 2 sec timeout]
--- FAIL: kuttl (2.51s)
FAIL
```

**What you expected to happen**:

`echo step two` (or any other later command) to **not** be run

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- KUTTL version (use `kubectl kuttl version`): `KUTTL Version: version.Info{GitVersion:"0.4.0", GitCommit:"b85c5a0", BuildDate:"2020-06-02T15:49:56Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by kensipe**
Please read issue #170 for more details.
The error handling of commands from a UX standpoint was confusing.   Now the first command to fail (that isn't registered to be ignored) will stop all other commands and will return that error.  It also logs the number of skipped commands.

The result of running the example provided in the issue is:

```
=== RUN   kuttl
    kuttl: harness.go:434: starting setup
    kuttl: harness.go:246: running tests using configured kubeconfig.
    kuttl: logger.go:42: 13:23:16 |  | running command: [sleep 3]
    kuttl: logger.go:42: 13:23:18 |  | command failure, skipping 1 additional commands
    kuttl: harness.go:479: cleaning up
    kuttl: harness.go:531: removing temp folder: ""
    kuttl: harness.go:555: fatal error running commands: command "sleep 3" exceeded 2 sec timeout
--- FAIL: kuttl (2.78s)
FAIL
```

Signed-off-by: Ken Sipe <kensipe@gmail.com>

Fixes #170

### CODE REVIEW

File: pkg/test/utils/kubernetes.go [hunk 1]
```diff
@@ -1077,19 +1077,22 @@ func RunCommand(ctx context.Context, namespace string, cmd harness.Command, cwd
 // RunCommands runs a set of commands, returning any errors.
 // If `command` is set, then `command` will be the command that is invoked (if a command specifies it already, it will not be prepended again).
 // commands running in the background are returned
```
Comment (ANeumann82) [inline pkg/test/utils/kubernetes.go:1079]:
```suggestion
// RunCommands runs a set of commands, returning any errors.
// If any (non-background) command fails, the following commands are skipped
// commands running in the background are returned
```

Comment (kensipe) [reply pkg/test/utils/kubernetes.go:1079]: good eye!  thank you
