### PR TITLE
Fixes Background Process Leaking Bug

### LINKED ISSUE #33: Kill of Background Processes Failing
The newly added technique to start a background process is working in testing but leaves the process running after exit.   It isn't clear yet why... theories:
1. the process exits too quickly for the kill to take place
2. the process is a grandchild (not a child) which go doesn't kill (frankly we may need to support killing all child and grandchild processes anyway.

for ref: https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773

### PR DESCRIPTION
**Pull request by kensipe**
Fixes #33 

Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

File: pkg/test/harness.go [hunk 1]
```diff
@@ -393,6 +402,16 @@ func (h *Harness) Stop() {
...
+	if h.bgProcesses != nil {
+		for _, p := range h.bgProcesses {
+			h.T.Log("killing process ", p)
+			err := p.Process.Kill()
+			if err != nil {
+				h.T.Log("background process kill error", err)
+			}
+		}
+	}
+
```
Comment (kensipe) [inline pkg/test/harness.go]: This needed to move up... the case below (which previously came before could return) leaking back processes

File: pkg/test/utils/kubernetes.go [hunk 2]
```diff
@@ -1006,24 +1006,24 @@ func RunCommands(logger Logger, namespace string, command string, commands []har
...
-			}
 		}
-
-		logger.Log(stderr.String())
-		logger.Log(stdout.String())
+		if bg != nil {
+			bgs = append(bgs, bg)
+		} else {
+			logger.Log(stderr.String())
+			logger.Log(stdout.String())
```
Comment (kensipe) [inline pkg/test/utils/kubernetes.go]: no logging if background

File: pkg/test/utils/kubernetes.go [hunk 3]
```diff
@@ -1006,24 +1006,24 @@ func RunCommands(logger Logger, namespace string, command string, commands []har
...
 		if err != nil {
 			errs = append(errs, err)
-			if bg != nil {
-				bgs = append(bgs, bg)
-			}
 		}
-
-		logger.Log(stderr.String())
-		logger.Log(stdout.String())
+		if bg != nil {
```
Comment (kensipe) [inline pkg/test/utils/kubernetes.go]: always add bg (this was the main bug)

File: pkg/test/harness.go [hunk 4]
```diff
@@ -393,6 +402,16 @@ func (h *Harness) Stop() {
 		}
 	}
 
+	if h.bgProcesses != nil {
```
Comment (zen-dog) [inline pkg/test/harness.go]: Fun fact, I've asked for a test for this case in the original #23 PR where this [bug was introduced](https://github.com/kudobuilder/kuttl/pull/23#discussion_r395609070) ;)

Comment (kensipe) [reply pkg/test/harness.go]: @zen-dog definitely!   added!

File: pkg/test/harness.go [hunk 5]
```diff
@@ -393,6 +402,16 @@ func (h *Harness) Stop() {
...
+		for _, p := range h.bgProcesses {
+			h.T.Log("killing process ", p)
+			err := p.Process.Kill()
+			if err != nil {
+				h.T.Log("background process kill error", err)
+			}
```
Comment (zen-dog) [inline pkg/test/harness.go]: Shouldn't we `Wait()` here for the process? 
```Wait waits for the Process to exit, and then returns a ProcessState describing its status and an error, if any. Wait releases any resources associated with the Process. On most operating systems, the Process must be a child of the current process or an error will be returned.```

File: pkg/test/harness_test.go [hunk 6]
```diff
@@ -81,3 +84,29 @@ func TestAddNodeCaches(t *testing.T) {
...
+	defer h.Stop()
+
+	// setup creates bg processes
+	assert.Equal(t, 1, len(h.bgProcesses))
+	// process is alive
+	assert.NoError(t, h.bgProcesses[0].Process.Signal(syscall.Signal(0)))
+
+	// cleans up bg processes
+	h.Stop()
+	_, err := h.bgProcesses[0].Process.Wait()
```
Comment (zen-dog) [inline pkg/test/harness_test.go]: See my comment above about waiting

File: pkg/test/harness.go (hunk 5 above)
Comment (kensipe) [reply pkg/test/harness.go]: @zen-dog I read the docs...  I'm not sure why we would want to wait... it doesn't add any value at this point

File: pkg/test/harness_test.go (hunk 6 above)
Comment (kensipe) [reply pkg/test/harness_test.go]: this wait is to ensure we don't have flaky tests

File: pkg/test/harness.go (hunk 5 above)
Comment (kensipe) [reply pkg/test/harness.go]: The termination of the test harness does not need to wait for other processes outside of its control to exit before exiting.   The harness is killing as we would expect.   Do we want the harness to hang because a user defined process is hanging?     If we were to `wait()` I would rewrite this such that the kill and waits are concurrent and wait for all routines to return.  this seems like a lot of complexity for no gain IMO

File: pkg/test/harness.go [hunk 7]
```diff
@@ -393,6 +402,23 @@ func (h *Harness) Stop() {
 		}
 	}
 
+	if h.bgProcesses != nil {
+		for _, p := range h.bgProcesses {
+			h.T.Log("killing process ", p)
+			err := p.Process.Kill()
+			if err != nil {
+				h.T.Log("background process kill error", err)
```
Comment (zen-dog) [inline pkg/test/harness.go]: Please log the process name in all places (L414 and L417)  (are command and arguments also available for logging?)

File: pkg/test/harness.go [hunk 8]
```diff
@@ -393,6 +402,23 @@ func (h *Harness) Stop() {
 		}
 	}
 
+	if h.bgProcesses != nil {
+		for _, p := range h.bgProcesses {
+			h.T.Log("killing process ", p)
+			err := p.Process.Kill()
+			if err != nil {
+				h.T.Logf("bg process: %v kill error %v", p, err)
```
Comment (zen-dog) [inline pkg/test/harness.go]:
```suggestion
				h.T.Logf("bg process: %q kill error %v", p, err)
```

Comment (zen-dog) [reply pkg/test/harness.go]: and the others too
