### PR TITLE
fixes nil ptr panic bug

### LINKED ISSUE #202: nil pointer dereference with kuttl 0.4.0
I've just run into the following nil pointer crash and thought I'd report it:

```
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry | Creating namespace: kudo-test-poetic-troll
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | starting test step 0-create
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | running command: "helm init --client-only"
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | running command: [helm init --client-only]
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | $HELM_HOME has been configured at /tekton/home/.helm.
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | Not installing Tiller due to 'client-only' flag having been set
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | running command: "helm delete --purge docker-registry"
    kuttl/harness/registry: logger.go:42: 17:25:15 | registry/0-create | running command: [helm delete --purge docker-registry]
    kuttl/harness/registry: logger.go:42: 17:25:26 | registry/0-create | Error: release: "docker-registry" not found
...
    kuttl/harness/registry: logger.go:42: 17:26:52 | registry/0-create | Error: release docker-registry failed: Get https://10.96.0.1:443/api/v1/namespaces/kudo-test-poetic-troll: dial tcp 10.96.0.1:443: connect: connection refused
    kuttl/harness/registry: case.go:156: exit status 1
    kuttl/harness/registry: case.go:156: Get "https://127.0.0.1:32768/api?timeout=32s": EOF
    kuttl/harness/registry: case.go:159: failed in step 0-create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x131e945]

goroutine 8260 [running]:
github.com/kudobuilder/kuttl/pkg/test/utils.(*RetryClient).List.func1(0x1936320, 0xc000046048, 0x0, 0x0)
	/Users/kensipe/projects/go/src/github.com/kudobuilder/kuttl/pkg/test/utils/kubernetes.go:228 +0x25
github.com/kudobuilder/kuttl/pkg/test/utils.Retry.func1(0xc0004670c0, 0x1936320, 0xc000046048, 0xc0006d5b60, 0xc0006d5ce0)
	/Users/kensipe/projects/go/src/github.com/kudobuilder/kuttl/pkg/test/utils/kubernetes.go:110 +0x3e
created by github.com/kudobuilder/kuttl/pkg/test/utils.Retry
	/Users/kensipe/projects/go/src/github.com/kudobuilder/kuttl/pkg/test/utils/kubernetes.go:109 +0xf7
Collecting kind cluster logs.
```

I believe this was with kuttl version 0.4.0.

### PR DESCRIPTION
**Pull request by kensipe**
Defensive recovery for retry logic on a goroutine which is using a shared reference to something that could be cleaned up.

Signed-off-by: Ken Sipe <kensipe@gmail.com>

Fixes #202

### CODE REVIEW

**Review by zmalik — APPROVED** [review]

File: pkg/test/utils/kubernetes.go [hunk 1]
```diff
@@ -102,12 +102,26 @@ func Retry(ctx context.Context, fn func(context.Context) error, errValidationFun
...
+	}
+
 	// do { } while (err != nil): https://stackoverflow.com/a/32844744/10892393
 	for ok := true; ok; ok = lastErr != nil {
 		// run the function in a goroutine and close it once it is finished so that
 		// we can use select to wait for both the function return and the context deadline.
 
 		go func() {
+			// if the func we are calling panics, clean up and call it done
+			// the common case is when a shared refernence, like a client, is nil and is called in the function
```
Comment (ANeumann82) [inline pkg/test/utils/kubernetes.go:117]:
```suggestion
			// the common case is when a shared reference, like a client, is nil and is called in the function
```

File: pkg/test/utils/kubernetes.go [hunk 2]
```diff
@@ -102,12 +102,26 @@ func Retry(ctx context.Context, fn func(context.Context) error, errValidationFun
...
+			defer func() {
+				if r := recover(); r != nil {
+					log.Println("retry func has panicked and will be ignored")
+					doneCh <- struct{}{}
```
Comment (ANeumann82) [inline pkg/test/utils/kubernetes.go:121]: Would it make more sense to `errCh <- fmt.Errorf("retry func has panicked")`?

I don't know enough about recovery, but it feels like it's an error?

**Review by ANeumann82 — APPROVED** [review]

File: pkg/test/utils/kubernetes.go (hunk 1 above)
Comment (kensipe) [reply pkg/test/utils/kubernetes.go:117]: good catch.. thx!

File: pkg/test/utils/kubernetes.go (hunk 2 above)
Comment (kensipe) [reply pkg/test/utils/kubernetes.go:121]: you are right... updated
