### PR TITLE
Report 0 testsuites and failed connections

### LINKED ISSUE #242: Report Always When Asked to Report
Current if KUTTL has a connection failure, or rbac issue could result in no tests when  `--report xml` is specified no report is generated.  This causes an issue in scorecard: https://github.com/operator-framework/operator-sdk/issues/4096 
It is expected that a report is always generated and if there is an error for the testsuite, that is communicated, allowing for communication via automation. 

Considering this a bug (I know... debatable :)

### PR DESCRIPTION
**Pull request by kensipe**
This PR provides the following benefits (read #242 for full context)

* if `--report` is specified, always report.  This will now report even if there are 0 test suites.
* if there is a connection issue the test is "failed".  If `--report` is specified, this will now report with the fatal error information.
* small adjustment for ` (h *Harness) fatal` which was always called with `error` which it was refactor to use.

Signed-off-by: Ken Sipe <kensipe@gmail.com>

Fixes #242

### CODE REVIEW

File: pkg/test/case.go [hunk 1]
```diff
@@ -196,6 +196,7 @@ func shortString(obj *corev1.ObjectReference) string {
 func (t *Case) Run(test *testing.T, tc *report.Testcase) {
 	ns := t.determineNamespace()
 	if err := t.CreateNamespace(ns); err != nil {
+		tc.Failure = report.NewFailure(err.Error(), nil)
```
Comment (jbarrick-mesosphere) [inline pkg/test/case.go:199]: Should we use AddFailure here?

File: pkg/report/report.go [hunk 2]
```diff
@@ -235,6 +234,13 @@ func (ts *Testsuites) NewSuite(name string) *Testsuite {
 	return suite
 }
 
+// AddFailure adds a failure to the TestSuites collection for startup failures in the test harness
+func (ts *Testsuites) AddFailure(message string) {
```
Comment (jbarrick-mesosphere) [inline pkg/report/report.go:238]: `SetFailure` might be better since it's not a list

**Review by jbarrick-mesosphere — APPROVED** [review]
A couple nits, but LGTM!

File: pkg/report/report.go (hunk 2 above)
Comment (kensipe) [reply pkg/report/report.go:238]: nice! thx

File: pkg/test/case.go (hunk 1 above)
Comment (kensipe) [reply pkg/test/case.go:199]: the `AddFailure` (renamed to `SetFailure`) is at the TestSuites (collection level).  This failure is at the testcase level and will report a failure for each test case if all namespaces can not be created).  It might be debatable if we need to report each one individual.. but if we want to fail the whole suite on 1 namespace creation issue we would need to report from this run... and we currently don't

**Review by jbarrick-mesosphere — APPROVED** [review]

**Review by jmccormick2001 — APPROVED** [review]
